[build.environment]
NODE_VERSION = "21"

[build]
publish = ".output"
command = "pnpm run build"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[[headers]]
for = "/*"
[headers.values]
Access-Control-Allow-Origin = "*"
